function escape(value: string): string {
  return value.replace(/[&<>"']/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]!);
}

export function authPage(options: { csrf: string; state?: string; clientName?: string; authenticated?: boolean; message?: string; nonce: string }): string {
  const oauth = Boolean(options.state);
  const title = oauth ? "Conectar ao Vitalis" : "Bem-vindo ao Vitalis";
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${title}</title><style>
  *{box-sizing:border-box}body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#0f172a;background:#f8fafc;min-height:100vh}header{height:76px;border-bottom:1px solid #e2e8f0;background:#fff;display:flex;align-items:center;padding:0 40px;gap:10px;font-weight:750;letter-spacing:-.03em;font-size:20px}.mark{width:34px;height:34px;border-radius:9px;background:#0f766e;color:#fff;display:grid;place-items:center;font-size:23px}header small{margin-left:auto;font-size:11px;font-weight:500;letter-spacing:0;color:#64748b;padding:6px 10px;border:1px solid #e2e8f0;border-radius:20px}main{display:grid;grid-template-columns:1fr 420px;align-items:center;gap:80px;width:min(1000px,calc(100% - 64px));margin:80px auto}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:11px;color:#0f766e;font-weight:750}.intro h1{font-size:44px;letter-spacing:-.055em;line-height:1.12;max-width:470px;margin:18px 0}.intro p{font-size:15px;color:#64748b;line-height:1.7;max-width:400px}.steps{padding:20px 0 0;list-style:none;color:#334155;font-size:13px}.steps li{margin:18px 0;display:flex;gap:10px;align-items:center}.check{border-radius:50%;background:#ccfbf1;color:#0f766e;width:21px;height:21px;display:grid;place-items:center;font-size:11px}.card{background:white;border:1px solid #e2e8f0;border-radius:14px;padding:34px;box-shadow:0 8px 24px #0f172a06}.card h2{margin:0 0 8px;font-size:23px;letter-spacing:-.04em}.card p{font-size:13px;color:#64748b;line-height:1.6;margin:0 0 26px}label{display:block;font-size:12px;font-weight:650;margin:17px 0 7px}input{width:100%;height:43px;border:1px solid #cbd5e1;border-radius:7px;padding:0 12px;font:inherit;font-size:14px;color:#0f172a}input:focus{outline:3px solid #ccfbf1;border-color:#0f766e}button{margin-top:25px;height:44px;border:0;border-radius:7px;background:#0f766e;color:white;font:inherit;font-size:13px;font-weight:650;width:100%;cursor:pointer}button:hover{background:#115e59}button:disabled{opacity:.6;cursor:wait}.note{padding-top:22px;margin-top:24px;border-top:1px solid #f1f5f9;font-size:11px;line-height:1.6;color:#64748b}.message{background:#fff1f2;color:#9f1239;padding:11px;border:1px solid #fecdd3;border-radius:7px;font-size:12px;margin:15px 0}footer{text-align:center;font-size:11px;color:#94a3b8;padding:12px 24px 32px}a{color:#0f766e}@media(max-width:780px){header{padding:0 22px}main{grid-template-columns:1fr;gap:24px;margin:40px auto;width:min(440px,calc(100% - 36px))}.intro h1{font-size:31px}.intro p,.steps{display:none}.card{padding:26px}.intro h1{margin-bottom:0}}
  </style></head><body><header><span class="mark">+</span>Vitalis<small>Ambiente de demonstração</small></header><main><section class="intro"><span class="eyebrow">Conferência preventiva de guias</span><h1>Mais clareza antes de cada envio.</h1><p>Confira regras, identifique pendências e organize as correções da sua operação em um só lugar.</p><ul class="steps"><li><span class="check">✓</span>Regras de convênios em uma consulta</li><li><span class="check">✓</span>Orientações para cada pendência</li><li><span class="check">✓</span>Histórico e indicadores confiáveis</li></ul></section><section class="card"><h2>${title}</h2><p>${oauth ? `${options.authenticated ? "Confirme o acesso" : "Entre com sua conta de demonstração para conectar"} ${escape(options.clientName || "seu assistente")}. O acesso permite consultar regras, verificar e registrar guias.` : "Acesse com as credenciais de demonstração recebidas."}</p>${options.message ? `<div role="alert" class="message">${escape(options.message)}</div>` : ""}<form method="POST" action="${oauth ? "/authorize" : "/login"}"><input type="hidden" name="csrf_token" value="${escape(options.csrf)}">${options.state ? `<input type="hidden" name="state" value="${escape(options.state)}">` : ""}${options.authenticated ? "" : `<label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="username" required maxlength="254" placeholder="voce@clinica.com.br"><label for="password">Senha</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024" placeholder="Sua senha">`}<button type="submit">${oauth ? "Autorizar conexão" : "Entrar no Vitalis"}</button></form><div class="note">${oauth ? "Autorize apenas aplicativos em que você confia. Você pode cancelar fechando esta página." : "O ambiente é compartilhado para avaliação. Use apenas dados fictícios nas guias."}</div></section></main><footer>Vitalis · Conferência preventiva de guias</footer><script nonce="${escape(options.nonce)}">document.querySelector('form').addEventListener('submit',function(){var b=this.querySelector('button');b.disabled=true;b.textContent='Aguarde…';});</script></body></html>`;
}
